// Generated by CoffeeScript 1.6.3
var analysic, analysicTitle, analysisParagraphs, bodyHtml, node, nodeIndex, paragraphs, targetDiv, titleEl;

bodyHtml = document.body.innerHTML;

targetDiv = null;

paragraphs = document.querySelectorAll("p");

analysisParagraphs = function() {
  var paragraph, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = paragraphs.length; _i < _len; _i++) {
    paragraph = paragraphs[_i];
    _results.push(analysic(paragraph));
  }
  return _results;
};

analysic = function(p) {
  var parentEl;
  parentEl = p.parentNode;
  if (!parentEl.easyreading) {
    parentEl.easyreading = {
      score: 0
    };
    if (parentEl.className.match(/(comment|meta|footer|footnote)/)) {
      parentEl.easyreading.score -= 50;
    } else {
      if (parentEl.className.match(/((^|\\s)(post|hentry|entry[-]?(content|text|body)?|article[-]?(content|text|body)?)(\\s|$))/)) {
        parentEl.easyreading.score += 25;
      }
    }
    if (parentEl.id.match(/(comment|meta|footer|footnote)/)) {
      parentEl.easyreading.score -= 50;
    } else {
      if (parentEl.id.match(/((^|\\s)(post|hentry|entry[-]?(content|text|body)?|article[-]?(content|text|body)?)(\\s|$))/)) {
        parentEl.easyreading.score += 25;
      }
    }
  }
  if (parentEl.innerText.length > 10) {
    parentEl.easyreading.score++;
  }
  parentEl.easyreading.score += parentEl.innerText.split(",").length;
  return parentEl.easyreading.score += parentEl.innerText.split("，").length;
};

analysisParagraphs();

nodeIndex = 0;

titleEl = [];

while ((node = document.getElementsByTagName('*')[nodeIndex]) != null) {
  if (node.className.match(/(title)/) || node.id.match(/(title)/) || node.tagName.match(/(H1|H2|H3|H4|H5|H6)/)) {
    titleEl.push(node);
  }
  if (node.easyreading != null) {
    if ((targetDiv == null) || node.easyreading.score > targetDiv.easyreading.score) {
      targetDiv = node;
    }
  }
  nodeIndex++;
}

console.log(targetDiv);

analysicTitle = function(t) {
  var head;
  if (head = t.tagName.match(/H(\d)/)) {
    if (!head.titlescore) {
      return head.titlescore;
    }
  }
};
